AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

swagger: '2.0'
info:
  title: AI Customer Service API
  description: 'AI Customer Service application, built during the Cloud and Big Data course at Columbia University.'
  version: 1.0.0

schemes:
  - https

basePath: /v1

produces:
  - application/json


# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
paths:
  /chatbot:

    post:
      tags:
        - NLU
      
      operationId: sendMessage

      produces:
        - application/json

      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/BotRequest' #these refs refer to the definitions below, which escribe the types of JSON objects that are either inputs or outputs

      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/BotResponse'

        '403':

          description: Unauthorized

          schema:

            $ref: '#/definitions/Error'

        '500':

          description: Unexpected error

          schema:

            $ref: '#/definitions/Error'

definitions:

  BotRequest:

    type: object

    properties:

      messages:

        type: array

        items:

          $ref: '#/definitions/Message'

  BotResponse:

    type: object

    properties:

      messages:

        type: array

        items:

          $ref: '#/definitions/Message'

  Message:

    type: object

    properties:

      type:

        type: string

      unstructured:

        $ref: '#/definitions/UnstructuredMessage'

  UnstructuredMessage:

    type: object

    properties:

      id:

        type: string

      text:

        type: string

      timestamp:

        type: string

        format: datetime

  Error:

    type: object

    properties:

      code:

        type: integer

        format: int32

      message:
        type: string
